name: "Azure App Service Deploy"
description: "Deploys code or containers to Azure App Services, verifies specific version health, and performs safe swaps."
author: "mharikmert"
branding:
  color: "blue"
  icon: "shield"

inputs:
  # --- Identity ---
  app_name:
    description: "Name of the Azure App Service."
    required: true
  resource_group:
    description: "Azure Resource Group."
    required: true
  slot_name:
    description: "The slot to deploy to initially (e.g., 'test')."
    required: true

  # --- Artifacts (One is required) ---
  package_path:
    description: "Path to zip file or folder (for Code mode)."
    required: false
  images:
    description: "Docker image tag(s) (for Container mode)."
    required: false

  # --- Verification ---
  health_check_path:
    description: "Path to poll for health (e.g., '/health')."
    required: false
    default: "/"
  expected_version:
    description: "If provided, the action polls until the endpoint returns this version."
    required: false

  # --- Strategy ---
  mode:
    description: "'prod' (swaps to target) or 'non-prod' (deploy only)."
    required: false
    default: "non-prod"
  swap_target:
    description: "Slot to swap into (only used in prod mode)."
    required: false
    default: "production"

runs:
  using: "node20"
  main: "dist/index.js"
